export const OBTENER_VALUE = "OBTENER_VALUE";
export const GUARDAR_BUSQUEDA_EXITO = "GUARDAR_JUGADOR_EXITO";
export const OBTENER_BUSQUEDA_ERROR = "OBTENER_JUGADOR_ERROR";
export const FETCH_EXITO = "FETCH_EXITO";
